### ISSUE TITLE
update rubocop to a current version

### ISSUE THREAD

**Issue by freibuis** [puppetlabs/puppet-module-gems#115]
```yaml
dev:
  shared:
    gem: rubocop
    version: '~> 0.49.0'
```
`0.49.0` has been out for almost 2 years now. version `0.74.0` has been out for over a month

the old version plays havoc with new gems like solargraph which require at least 0.54 to work correctly
